# Generated by Django 5.1 on 2024-08-10 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='menu',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
    ]
