# Generated by Django 5.1 on 2024-08-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address2',
            new_name='resturant_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
