# Generated by Django 5.1 on 2024-09-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_product_price_portion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
    ]
