# Generated by Django 5.1 on 2024-10-01 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_product_is_sale_remove_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='main.product'),
        ),
    ]
