# Generated by Django 4.2.16 on 2024-10-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
